name: pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - run: ruff check

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test

  test:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - run: pytest
      - name: Failure Reporting
        if: failure()
        run: echo "TODO generate report"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: build-image
        run: |
          echo "use docker to build and push to container registry"
  deploy:
    needs: build
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        run: |
          echo "deploy to host provider"